"""initial

Revision ID: 17d94f243945
Revises: 
Create Date: 2026-08-23 04:33:09.711974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d94f243945'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('contact_person', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_username'), ['username'], unique=True)

    op.create_table('category_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'teacher_id')
    )
    with op.batch_alter_table('category_teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_teachers_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('class_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('grade_level', sa.String(length=8), nullable=False),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('homeroom_teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('admin_note', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_class_group_id'), ['class_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_student_id'), ['student_id'], unique=True)

    op.create_table('loan_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_periods_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_periods_student_id'), ['student_id'], unique=False)

    op.create_table('student_bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_bans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_bans_student_id'), ['student_id'], unique=False)

    op.create_table('borrowing_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('loan_period_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('student_note', sa.String(length=256), nullable=True),
    sa.Column('teacher_note', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation', sa.String(length=16), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['loan_period_id'], ['loan_periods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date')
    )
    with op.batch_alter_table('borrowing_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_borrowing_requests_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_borrowing_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_borrowing_requests_status'))
        batch_op.drop_index(batch_op.f('ix_borrowing_requests_date'))

    op.drop_table('borrowing_requests')
    with op.batch_alter_table('student_bans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_bans_student_id'))

    op.drop_table('student_bans')
    with op.batch_alter_table('loan_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_periods_student_id'))
        batch_op.drop_index(batch_op.f('ix_loan_periods_category_id'))

    op.drop_table('loan_periods')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_students_class_group_id'))

    op.drop_table('students')
    op.drop_table('class_groups')
    with op.batch_alter_table('category_teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_teachers_teacher_id'))

    op.drop_table('category_teachers')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_username'))

    op.drop_table('teachers')
    op.drop_table('categories')
    # ### end Alembic commands ###
