"""add AssignedReviewer

Revision ID: c03522d1f85b
Revises: 17d94f243945
Create Date: 2026-09-06 05:03:48.358604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03522d1f85b'
down_revision = '17d94f243945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['borrowing_requests.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'teacher_id')
    )
    with op.batch_alter_table('assigned_reviewers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assigned_reviewers_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assigned_reviewers_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_reviewers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assigned_reviewers_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_assigned_reviewers_request_id'))

    op.drop_table('assigned_reviewers')
    # ### end Alembic commands ###
